name: Bake docker images

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Application to tag (api, fastify-api, or all)'
        required: true
        default: 'api'
        type: choice
        options:
          - api
          - fastify-api
      version:
        description: Aplication version
        type: text
        default: 0.0.0
jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-${{ github.event.inputs.app_name }}
          tags: |
            type=semver,pattern={{version}},value=${{  github.event.inputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ github.event.inputs.version }}
            type=semver,pattern={{major}},value=${{ github.event.inputs.version }}
            type=raw,value=latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.title=Obsequia Assistant - ${{ github.event.inputs.app_name }}
            org.opencontainers.image.vendor=Obseqia, Inc.
            org.opencontainers.image.created=${{ github.event.repository.created_at }}
            org.opencontainers.image.version=${{ github.event.inputs.version }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/bake-action@v6
        with:
          source: https://github.com/obseqia/obseqia-api.git#main
          push: true
          files: docker-bake.hcl
          targets: ${{ github.event.inputs.app_name }}
          set: |
            *.tags+=${{ steps.meta.outputs.tags }}
            *.labels+=${{ steps.meta.outputs.labels }}
